name: sehati
description: منصة صحتي — سكر، ضغط، وثائق طبية
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3

  # Notifications & Alarms
  flutter_local_notifications: ^17.0.0
  android_alarm_manager_plus: ^3.0.3
  permission_handler: ^11.3.0

  # UI
  fl_chart: ^0.68.0
  intl: ^0.19.0
  google_fonts: ^6.1.0

  # WhatsApp / Share
  url_launcher: ^6.2.4
  share_plus: ^7.2.2

  # Camera / Files
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
